version: '3.7'
services:
  app:
    image: image-regression-notification
    build:
      context: .
    env_file:
      - .env
    environment:
      BASE_URL: ${BASE_URL}
      COMPARE_URL: ${COMPARE_URL}
    volumes:
      - ./dist:/app/dist
      - ./src:/app/src
